### ISSUE TITLE
육각형 아키텍처 설계시 코드 재사용을 어떤 식으로 하시는지 알고 싶습니다.

### ISSUE THREAD

**Issue by Hyune-c** [geminiKim/dev-practice#12]
```kotlin
// controller
class AuthController(private val authUsecase: AuthUsecase) {
    fun signin(@RequestBody request: UserSigninRequest): UserSigninResponse {
// ... usecase 호출해서 response 생성
    }
}


// usecase 
interface AuthUsecase {
    fun signin(username: String, password: String): String
}


// 구현체 (service, adapter)
class AuthService(
    private val userUsecase: UserUsecase
) : AuthUsecase {
    override fun signin(username: String, password: String): String {
        return userUsecase.findByUsername(username).let {
            //  ... 비밀번호 매칭시키고 jwt 반환하는 로직
        }
    }
}
```

안녕하세요. 요즘 육각형 아키텍처에 대해 학습하고 있는데 의문이 들어 질문 드립니다.
질문을 잘 설명하기 위해  슈도 코드를 가져 왔습니다.

## 배경

AuthController 는 AuthUsecase 인터페이스를 선언하고, AuthService 는 AuthUsecase 를 구현해서 주입하는 형태 입니다.
User 또한 비슷한 구조 입니다.

## 질문 & 제 생각

>  usecase, service 구현을 위해 위해 타 애그리거트의 정보를 가져와야 될 때 어느 레벨로 접근해야 될까?

```
- usecase 레벨로 가져와도 되는가?
- 구현체 (service) 레벨로 가져와야 되는 거 아닐까?
- 어쩌면 더 나아가 영속성 레벨까지 구현해야되는 것 아닐까?
```

- usecase 레벨로 가져와도 됩니다.
- 대신 기존의 구현체를 사용하는 것이 아닌 적절한 구현체를 구현하고 주입해야 됩니다.
    - 즉 하나의 usecase 에 대해 다수의 구현체가 생성될 수 있습니다.
    - 아마 `@Qualifier` 등을 통해 주입할 구현체를 지정해야 될 것 같습니다.
- 이 경우 우려되는 점은 다수의 구현체를 만족하기 위해 usecase 의 메서드가 늘어날 수 있습니다.

> 근데 막상 질문과 제 생각을 적다보니 `usecase 활용을 통해 재사용성을 높인 것 처럼 말하지만` 결국 구현체를 통으로 다시 만드는 것임으로 재사용성이 떨어집니다.

- 그렇다면 그냥 usecase 를 통하지 않고 독립적으로 만드는게 맞는 것인가..?
- 개인적으로는 재사용보다는 코드 양이 늘더라도 명시적인 구분이 더 좋다고 생각합니다.
- 위 내용에 관련해서 생각하시는 내용을 듣고 싶습니다.

## 참고 자료

[네이버파이낸셜 - 프로젝트에 새로운 아키텍처 적용하기](https://medium.com/naverfinancial/%ED%94%84%EB%A1%9C%EC%A0%9D%ED%8A%B8%EC%97%90-%EC%83%88%EB%A1%9C%EC%9A%B4-%EC%95%84%ED%82%A4%ED%85%8D%EC%B2%98-%EC%A0%81%EC%9A%A9%ED%95%98%EA%B8%B0-99d70df6122b)

![image](https://github.com/team-dodn/devgem-topic/assets/55722186/ca50fcc3-7ba2-49b0-8dad-bd0f3c6863c1)

**Comment by geminiKim** [comment]
질문 감사합니다! 차후에 다뤄보도록 하겠습니다!👍

**Comment by geminiKim** [comment]
to: https://youtu.be/ruvjrehGmT0
