### ISSUE TITLE
문제해결 능력과 사용자 중심 사고 능력을 기를 수 있는 방법은 무엇일까요?

### ISSUE THREAD

**Issue by JerryK026** [geminiKim/dev-practice#13]
안녕하세요, 요즘 유튜브 영상 자주 올려주셔서 재밌게 잘 보고 있습니다 감사합니다 ㅎ

개인적으로 최근 AI 발전과 기술들의 발전에 따라 개발자들 개인의 기술적 역량 보다 문제 해결 능력이나, 더 나은 서비스를 위한 고민하는 능력을 가진 개발자가 되어야 미래에도 더 경쟁력 있는 개발자가 되지 않을까 하는 생각을 가지고 있습니다.

최근 들어 공고들에서 소프트 스킬이나 문제 해결 경험을 요구하는 회사들이 늘어나는 것도 그 이유가 아닐까 추측하고 있습니다.

그런데 기업들에서 요구하는 그 문제 해결 능력은 어떻게 기를 수 있을까요? 단순히 자신만의 프로덕트를 만들어 보고 그 프로덕트를 개선하기 위해 노력한 것을 문제 해결이라고 볼 수 있을까요?

그리고 나름대로 문제 해결을 위해 많이 고민하고 프로덕트를 만든다고 해도 트래픽이나 수익이 나오지 않는다면 그건 문제를 옳게 해결했다고 볼 수 없을까요?

문제 해결을 위해 문제를 잘 인식하려면 사전에 어떤 과정을 거쳐야 하며, 기술이 아니라 정책으로 풀어낼 수 있는 경지에 이르려면 도메인 지식 외 무엇이 필요할까요?

재미니 님께서는 "문제", "문제 인식 능력", "문제 해결 능력", "사용자 중심 사고 능력" 이 키워드들에 대해 어떻게 생각하시고 정의 하시는지 궁금하고, 여태 만나온 수많은 주니어들을 보면서 학생들이나 취준생, 주니어들이 기술 뿐만 아니라 어떠한 걸 고려하면서 능력을 길렀으면 생각하신 부분이 있으신지 궁금합니다.

취준생 입장에서 궁금한 점들이 참 많아 질문이 많아졌네요.

감사합니다 ㅎㅎ

**Comment by geminiKim** [comment]
to: https://youtu.be/RoKL6KKxZ_A?si=-Ty5N96BXzpUwv-d
